### ISSUE TITLE
send campaign fails with server exception

### ISSUE THREAD

**Issue by thg303** [jpalumickas/mailerlite-ruby#4]
is it an API bug or gem bug?

```
client.campaign_action(campaign.id, 'send')  
MailerLite::InternalServerError: The server encountered an unexpected condition
	from /home/ali/projects/ruby/mailerlite-ruby/lib/mailerlite/middleware/raise_error.rb:11:in `on_complete'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:9:in `block in call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/response.rb:8:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.1/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.10.1/lib/faraday_middleware/request/encode_json.rb:23:in `call'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
	from /home/ali/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faraday-0.11.0/lib/faraday/connection.rb:177:in `post'
	from /home/ali/projects/ruby/mailerlite-ruby/lib/mailerlite/connection.rb:37:in `request'
	from /home/ali/projects/ruby/mailerlite-ruby/lib/mailerlite/connection.rb:27:in `post'
	from /home/ali/projects/ruby/mailerlite-ruby/lib/mailerlite/clients/campaigns.rb:50:in `campaign_action'
	from (irb):47
	from ./bin/console:14:in `<main>'
```

**Comment by jpalumickas** [comment]
Hey, 
This is API bug. They returned 500 status.

**Comment by thg303** [comment]
Hi,
I got it. it happens when the language was set to "fa", when it was set to "en" there was no interneal error.

**Comment by jpalumickas** [comment]
Ok, perfect! Let me know if there will be any problems 👍
